import fs from "fs";
import os from "os";
import path from "path";
import { readSettings } from "@/lib/data";
import { getCloudProviders } from "@/lib/cloud-providers-service";
import { getSessionSecrets } from "@/lib/cloud-session-service";
import { parseBilibiliUrl } from "@/lib/media-resolver";

export interface PlatformSession {
  bilibiliCookie?: string;
  baiduCookie?: string;
  ytdlpBrowser?: string;
}

function normalizeCookieString(raw?: string): string | undefined {
  const t = raw?.trim();
  return t || undefined;
}

/** 从设置 + 已连接网盘会话 + 环境变量汇总平台 Cookie */
export async function getPlatformSession(
  sourceUrl?: string
): Promise<PlatformSession> {
  const settings = await readSettings();
  const bilibiliCookie =
    normalizeCookieString(settings.bilibiliCookies) ||
    normalizeCookieString(process.env.BILIBILI_COOKIES);

  const ytdlpBrowser =
    normalizeCookieString(settings.ytdlpCookiesFromBrowser) ||
    normalizeCookieString(process.env.YTDLP_COOKIES_FROM_BROWSER);

  let baiduCookie: string | undefined;
  const providers = getCloudProviders();
  const baidu = providers.find((p) => p.connected && p.type === "baidu");
  if (baidu) {
    const secrets = getSessionSecrets(baidu.id);
    if (secrets?.cookies) {
      baiduCookie = secrets.cookies;
    } else if (secrets?.bduss) {
      baiduCookie = `BDUSS=${secrets.bduss}${secrets.stoken ? `; STOKEN=${secrets.stoken}` : ""}`;
    }
  }

  // 百度分享链接优先用网盘 Cookie
  if (sourceUrl && isBaiduPanUrl(sourceUrl) && baiduCookie && !bilibiliCookie) {
    return { bilibiliCookie, baiduCookie, ytdlpBrowser };
  }

  return { bilibiliCookie, baiduCookie, ytdlpBrowser };
}

export function isBaiduPanUrl(url: string): boolean {
  try {
    const u = new URL(url);
    return (
      u.hostname.includes("pan.baidu.com") ||
      u.hostname.includes("yun.baidu.com")
    );
  } catch {
    return false;
  }
}

/** B站 API / 下载请求头 */
export function bilibiliFetchHeaders(
  bvid: string,
  cookie?: string
): Record<string, string> {
  return {
    "User-Agent":
      "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    Referer: `https://www.bilibili.com/video/${bvid}/`,
    Origin: "https://www.bilibili.com",
    ...(cookie ? { Cookie: cookie } : {}),
  };
}

let cachedCookiesFile: { path: string; content: string } | null = null;

/** 为 yt-dlp 生成 Netscape cookies 临时文件（支持 b 站 / 百度 Cookie 字符串） */
export function writeYtDlpCookiesFile(cookieHeader: string): string {
  if (cachedCookiesFile?.content === cookieHeader) {
    return cachedCookiesFile.path;
  }
  const lines = ["# Netscape HTTP Cookie File", "# Generated by LangTube"];
  const pairs = cookieHeader.split(";").map((p) => p.trim());
  const domainsFor = (name: string, pair: string): string[] => {
    if (name.includes("BAIDU") || pair.includes("STOKEN") || name === "BDUSS") {
      return [".baidu.com", "pan.baidu.com"];
    }
    return [".bilibili.com", "www.bilibili.com", ".bilivideo.com"];
  };
  for (const pair of pairs) {
    const eq = pair.indexOf("=");
    if (eq <= 0) continue;
    const name = pair.slice(0, eq).trim();
    const value = pair.slice(eq + 1).trim();
    if (!name || !value) continue;
    for (const domain of domainsFor(name, pair)) {
      lines.push(`${domain}\tTRUE\t/\tFALSE\t0\t${name}\t${value}`);
    }
  }
  const filePath = path.join(
    os.tmpdir(),
    `langtube-cookies-${Date.now()}.txt`
  );
  fs.writeFileSync(filePath, lines.join("\n"));
  cachedCookiesFile = { path: filePath, content: cookieHeader };
  return filePath;
}

/**
 * yt-dlp 多种鉴权方式（按稳定性排序）。
 * B站 Cookie 文件优先于 chrome——Next.js 子进程常无法读取浏览器 Cookie 库。
 */
export async function getYtDlpAuthAttempts(
  sourceUrl?: string
): Promise<string[][]> {
  const session = await getPlatformSession(sourceUrl);
  const attempts: string[][] = [];
  const bili = sourceUrl ? parseBilibiliUrl(sourceUrl) : null;
  const baidu = sourceUrl ? isBaiduPanUrl(sourceUrl) : false;

  if (bili && session.bilibiliCookie) {
    attempts.push([
      "--cookies",
      writeYtDlpCookiesFile(session.bilibiliCookie),
    ]);
  }
  if (baidu && session.baiduCookie) {
    attempts.push(["--cookies", writeYtDlpCookiesFile(session.baiduCookie)]);
  }
  if (session.ytdlpBrowser) {
    attempts.push(["--cookies-from-browser", session.ytdlpBrowser]);
  }
  if (!bili && session.bilibiliCookie) {
    attempts.push([
      "--cookies",
      writeYtDlpCookiesFile(session.bilibiliCookie),
    ]);
  }
  if (!baidu && session.baiduCookie) {
    attempts.push(["--cookies", writeYtDlpCookiesFile(session.baiduCookie)]);
  }

  return attempts;
}

/** yt-dlp 额外参数：取首选鉴权方式 */
export async function getYtDlpAuthArgs(sourceUrl?: string): Promise<string[]> {
  const attempts = await getYtDlpAuthAttempts(sourceUrl);
  return attempts[0] ?? [];
}

export async function hasPlatformLogin(sourceUrl?: string): Promise<boolean> {
  const s = await getPlatformSession(sourceUrl);
  return Boolean(s.bilibiliCookie || s.baiduCookie || s.ytdlpBrowser);
}
